services:
  jupyter:
    build: .
    ports:
      - "8888:8888"
    volumes:
      - ./data:/thesis/data
      - ./models:/thesis/models
      - ./helper:/thesis/notebooks/helper
      - ./notebooks:/thesis/notebooks
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]